# Generated by Django 2.0.2 on 2018-02-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20180212_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='closingtime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='openingtime',
            field=models.TimeField(),
        ),
    ]
