# Generated by Django 2.0.2 on 2018-02-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
